### ISSUE TITLE
Self-destructing "Identity Verified" messages

### ISSUE THREAD

**Issue by jackharrhy** [MUNComputerScienceSociety/Automata#14]
the process of users verifying their accounts can be a bit _loud_ when we get a wave of users joining, so both the users message and the message from the bot _could_ be removed after a given timeout.

Alternative to this is to only permit verification within DMs, but this is also a bit limiting / less easy than just jumping into the guild and pasting it into the textbox and being _done_

**Comment by SteveParson** [comment]
I like this!
