### ISSUE TITLE
Fix drone builds

### ISSUE THREAD

**Issue by jackharrhy** [MUNComputerScienceSociety/Automata#3]
![image](https://user-images.githubusercontent.com/6486417/66354408-4c127400-e93f-11e9-8f69-46d689d3bc09.png)

builds are wonky! :(

https://drone.rileyflynn.me/MUNComputerScienceSociety/Automata

**Comment by nint8835** [comment]
Drone released a breaking change that made it treat servers as being multi-machine instances unless otherwise specified. I have specified otherwise, and the builds now work.
