### ISSUE TITLE
Twitch notification cog

### ISSUE THREAD

**Issue by jackharrhy** [MUNComputerScienceSociety/Automata#32]
Would be nice to have notifications for then Dave goes online on twitch

https://github.com/eriknyquist/twitch_monitor_discord_bot

^ seems like a good base

**Comment by TheEnderDruid** [comment]
I don't understand the bot enough to implement this, but wouldn't it just work to use the on_member_update() event? After all, Dave's streams appear as his activity in discord. For example, something roughly like this:
async def on_member_update(x, y):
     if y.name == "DaveChurchill" and y.Activity.type == ActivityType.Streaming : 
          and then send a message that includes y.Streaming.url

**Comment by jackharrhy** [comment]
@TheEnderDruid if Dave has his Twitch connected to his Discord, that's def. a potential method 🤔

**Comment by zcvaters** [comment]
Steam moved to Youtube
