### ISSUE TITLE
Remind users to authenticate their MUN accounts

### ISSUE THREAD

**Issue by jackharrhy** [MUNComputerScienceSociety/Automata#4]
- Course-specific channels are currently locked-off to those who have not authenticated themselves through DiscordAuth
- They are sent an initial message by the bot, but a considerable amount don't seem to be signing up!

----

Possible solutions / things to do to cut down on the number of said users:

- Add all users on join to an 'unauthenticated' role, therefore we can ping them ourselves to git-outta that role or git-outta the server. (might require manual one-time-only run to tag any user without any roles as an 'unauthentic' :older_man: role once this starts up for the first time once this change is made)
- Every couple days / weeks, bot messages users privately again, reminding them that they don't see all the channels on the server, and that they should go auth.

**Comment by Mudkip** [comment]
Relevant? Course-specific channels have been unlocked for quite a while now.

**Comment by jackharrhy** [comment]
@Mudkip not relevant, thanks for making a note of this :D
