### ISSUE TITLE
Course Plugin

### ISSUE THREAD

**Issue by HaMoOoOd25** [MUNComputerScienceSociety/Automata#92]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/45039279/136856705-aac14744-714b-493a-9c4b-8e65350f0933.png">

**Comment by jackharrhy** [comment]
should be fixed as of https://github.com/MUNComputerScienceSociety/Automata/commit/55bd3e3b99373015a10bff6aca289c1d168c3825
